package main

import (
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// cmdIcons fetches every icon a manifest lists from the Iconify API
// into -out, NORMALIZED (gradients flattened, em-sizes stripped) so
// the runtime never does text surgery. Manifest lines are
// "<set>:<icon> <file.svg>"; blank lines are skipped. The result is
// meant to be committed and embedded — the one moment the icon
// pipeline touches the network.
//
// Positional args are refs to ADD first: any icon on
// icon-sets.iconify.design, pasted as "<set>:<icon>" (optionally
// "<set>:<icon>=filename"), is appended to the manifest and then
// fetched with everything else — browse, copy, one command, commit.
//
// With -gen, a Go file of typed icon-name constants is generated from
// the manifest, so a typo'd or removed icon is a COMPILE error
// instead of a silently blank square at runtime.
func cmdIcons(args []string) error {
	fs := flagSet("icons")
	manifest := fs.String("manifest", "assets/icons/manifest.txt", "manifest file: one \"<set>:<icon> <file.svg>\" per line")
	out := fs.String("out", "assets/icons", "directory to write the SVGs into")
	gen := fs.String("gen", "", "generate a Go file of icon-name constants at this path")
	genPkg := fs.String("genpkg", "main", "package name for the generated constants file")
	fs.Parse(args)

	for _, ref := range fs.Args() {
		if err := addToManifest(*manifest, ref); err != nil {
			return err
		}
	}

	data, err := os.ReadFile(*manifest)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(*out, 0o755); err != nil {
		return err
	}
	var names []string
	for _, line := range strings.Split(string(data), "\n") {
		fields := strings.Fields(line)
		if len(fields) != 2 {
			if len(fields) != 0 {
				return fmt.Errorf("bad manifest line: %q", line)
			}
			continue
		}
		ref, file := fields[0], fields[1]
		names = append(names, strings.TrimSuffix(file, ".svg"))
		set, icon, ok := strings.Cut(ref, ":")
		if !ok {
			return fmt.Errorf("bad icon ref %q (want set:icon)", ref)
		}
		url := "https://api.iconify.design/" + set + "/" + icon + ".svg"
		fmt.Printf("  %s -> %s\n", ref, filepath.Join(*out, file))
		resp, err := http.Get(url)
		if err != nil {
			return err
		}
		body, err := io.ReadAll(resp.Body)
		resp.Body.Close()
		if err != nil {
			return err
		}
		if resp.StatusCode != http.StatusOK {
			return fmt.Errorf("%s: HTTP %d", url, resp.StatusCode)
		}
		if err := os.WriteFile(filepath.Join(*out, file), normalizeSVG(body), 0o644); err != nil {
			return err
		}
	}
	if *gen != "" {
		return writeIconConstants(*gen, *genPkg, names)
	}
	return nil
}

// writeIconConstants emits one exported constant per icon —
// IconEyeOff = "eye-off" — so call sites get compile-time checking.
func writeIconConstants(path, pkg string, names []string) error {
	sort.Strings(names)
	var b strings.Builder
	fmt.Fprintf(&b, "// Code generated by lotusui icons; DO NOT EDIT.\n\npackage %s\n\n", pkg)
	fmt.Fprintf(&b, "// Typed names for every icon in the manifest — a removed or\n// misspelled icon fails at COMPILE time, not as a blank square.\nconst (\n")
	for _, n := range names {
		fmt.Fprintf(&b, "\tIcon%s = %q\n", camel(n), n)
	}
	fmt.Fprintf(&b, ")\n")
	fmt.Printf("  constants -> %s (%d icons)\n", path, len(names))
	return os.WriteFile(path, []byte(b.String()), 0o644)
}

// camel turns "eye-off" into "EyeOff".
func camel(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '-' || r == '_' })
	var b strings.Builder
	for _, p := range parts {
		b.WriteString(strings.ToUpper(p[:1]) + p[1:])
	}
	return b.String()
}

// addToManifest appends "<set>:<icon> <name>.svg" unless the ref is
// already listed. ref may carry an explicit name: "tabler:rocket=go".
func addToManifest(manifest, ref string) error {
	ref, name, named := strings.Cut(ref, "=")
	set, icon, ok := strings.Cut(ref, ":")
	if !ok || set == "" || icon == "" {
		return fmt.Errorf("bad icon ref %q (want set:icon, e.g. tabler:rocket)", ref)
	}
	if !named {
		name = icon
	}
	data, err := os.ReadFile(manifest)
	if err != nil && !os.IsNotExist(err) {
		return err
	}
	for _, line := range strings.Split(string(data), "\n") {
		if f := strings.Fields(line); len(f) == 2 && f[0] == ref {
			return nil // already listed
		}
	}
	entry := fmt.Sprintf("%s %s.svg\n", ref, name)
	body := string(data)
	if body != "" && !strings.HasSuffix(body, "\n") {
		body += "\n"
	}
	fmt.Printf("  manifest += %s", entry)
	return os.WriteFile(manifest, []byte(body+entry), 0o644)
}
