package main

import (
	"fmt"
	"image/color"
	"os"
	"strings"

	lotusui "github.com/ikaito-com/lotusui"
)

// cmdGenScales regenerates the library's stock color scales as
// LITERALS (scales_gen.go): the HSL grading runs here, at build time,
// so the shipped package carries plain values — zero init-time math,
// and every hex visible in the source and on pkg.go.dev. Run via the
// go:generate directive in scales.go.
func cmdGenScales(args []string) error {
	fs := flagSet("gen-scales")
	out := fs.String("o", "scales_gen.go", "output file (package lotusui)")
	fs.Parse(args)

	anchors := []struct {
		name string
		c    color.NRGBA
	}{
		{"Gray", color.NRGBA{R: 0x71, G: 0x80, B: 0x96, A: 0xFF}},
		{"Red", color.NRGBA{R: 0xE5, G: 0x3E, B: 0x3E, A: 0xFF}},
		{"Orange", color.NRGBA{R: 0xDD, G: 0x6B, B: 0x20, A: 0xFF}},
		{"Yellow", color.NRGBA{R: 0xD6, G: 0x9E, B: 0x2E, A: 0xFF}},
		{"Green", color.NRGBA{R: 0x38, G: 0xA1, B: 0x69, A: 0xFF}},
		{"Teal", color.NRGBA{R: 0x31, G: 0x97, B: 0x95, A: 0xFF}},
		{"Blue", color.NRGBA{R: 0x31, G: 0x82, B: 0xCE, A: 0xFF}},
		{"Cyan", color.NRGBA{R: 0x00, G: 0xB5, B: 0xD8, A: 0xFF}},
		{"Purple", color.NRGBA{R: 0x80, G: 0x5A, B: 0xD5, A: 0xFF}},
		{"Pink", color.NRGBA{R: 0xD5, G: 0x3F, B: 0x8C, A: 0xFF}},
	}

	var b strings.Builder
	b.WriteString("// Code generated by lotusui gen-scales; DO NOT EDIT.\n\npackage lotusui\n\nimport \"image/color\"\n\n")
	b.WriteString("// The stock scales: ten familiar hues, each graded from its anchor\n// at BUILD time — plain values, no init-time math. Use them directly\n// (Teal.C100), as button schemes (Teal.Scheme()), or as a starting\n// point for a Palette.\nvar (\n")
	for _, a := range anchors {
		s := lotusui.ScaleFrom(a.c)
		fmt.Fprintf(&b, "\t%s = ColorScale{\n", a.name)
		steps := []struct {
			f string
			c color.NRGBA
		}{
			{"C50", s.C50}, {"C100", s.C100}, {"C200", s.C200}, {"C300", s.C300}, {"C400", s.C400},
			{"C500", s.C500}, {"C600", s.C600}, {"C700", s.C700}, {"C800", s.C800}, {"C900", s.C900},
		}
		for _, st := range steps {
			fmt.Fprintf(&b, "\t\t%s: color.NRGBA{R: 0x%02X, G: 0x%02X, B: 0x%02X, A: 0xFF},\n", st.f, st.c.R, st.c.G, st.c.B)
		}
		b.WriteString("\t}\n")
	}
	b.WriteString(")\n")
	fmt.Printf("  scales -> %s\n", *out)
	return os.WriteFile(*out, []byte(b.String()), 0o644)
}
